
// Type definitions

typedef enum TooltipType
{
  TOOLTIPTYPE_NONE,
  TOOLTIPTYPE_EMPTY_TILE,
  TOOLTIPTYPE_TILE_WITH_TOOLTIP,
  TOOLTIPTYPE_SHROUD,
  TOOLTIPTYPE_UNIT,
  TOOLTIPTYPE_BUILDING,
  TOOLTIPTYPE_ENEMY_UNIT,
  TOOLTIPTYPE_ENEMY_BUILDING,
  TOOLTIPTYPE_NEUTRAL_UNIT,
  TOOLTIPTYPE_NEUTRAL_BUILDING,
  TOOLTIPTYPE_BUILD_UNIT,
  TOOLTIPTYPE_BUILD_BUILDING,
  TOOLTIPTYPE_STARPORT_UNIT,
  TOOLTIPTYPE_UPGRADE_BUILDING,
  TOOLTIPTYPE_SIDEBAR_BUTTON,
  TOOLTIPTYPE_POWER,
  TOOLTIPTYPE_CREDITS,
  TOOLTIPTYPE_RADAR_HOUSE_IMAGE,
  TOOLTIPTYPE_RADAR_MAP
} TooltipType;

typedef struct TooltipExtraData
{
  char text[100];
  int width;
  int color;
} TooltipExtraData;

// Variables

#define TOOLTIP_LINES 10

extern TooltipExtraData gTooltipExtraData[TOOLTIP_LINES];
