%include "macros/patch.inc"
%include "macros/datatypes.inc"
%include "patch.inc"

gfile Cursor0Data, "files/cursor/cursor0.ani"
gfile Cursor1Data, "files/cursor/cursor1.ani"
gfile Cursor2Data, "files/cursor/cursor2.ani"
gfile Cursor3Data, "files/cursor/cursor3.ani"
gfile Cursor4Data, "files/cursor/cursor4.ani"
gfile Cursor5Data, "files/cursor/cursor5.ani"
gfile Cursor6Data, "files/cursor/cursor6.ani"
gfile Cursor7Data, "files/cursor/cursor7.ani"
gfile Cursor8Data, "files/cursor/cursor8.ani"
gfile Cursor9Data, "files/cursor/cursor9.ani"
gfile Cursor10Data, "files/cursor/cursor10.ani"
gfile Cursor11Data, "files/cursor/cursor11.ani"
gfile Cursor12Data, "files/cursor/cursor12.ani"
gfile Cursor13Data, "files/cursor/cursor13.ani"
gfile Cursor14Data, "files/cursor/cursor14.ani"
gfile Cursor15Data, "files/cursor/cursor15.ani"
gfile Cursor16Data, "files/cursor/cursor16.ani"
gfile Cursor17Data, "files/cursor/cursor17.ani"
gfile Cursor18Data, "files/cursor/cursor18.ani"
gfile Cursor19Data, "files/cursor/cursor19.ani"
gfile Cursor20Data, "files/cursor/cursor20.ani"
gfile Cursor21Data, "files/cursor/cursor21.ani"
gfile Cursor22Data, "files/cursor/cursor22.ani"
gfile Cursor23Data, "files/cursor/cursor23.ani"
gfile Cursor24Data, "files/cursor/cursor24.ani"
gfile Cursor25Data, "files/cursor/cursor25.ani"
gfile Cursor26Data, "files/cursor/cursor26.ani"
gfile Cursor27Data, "files/cursor/cursor27.ani"
gfile Cursor28Data, "files/cursor/cursor28.ani"
gfile Cursor29Data, "files/cursor/cursor29.ani"
gfile Cursor30Data, "files/cursor/cursor30.ani"
gfile Cursor31Data, "files/cursor/cursor31.ani"
gfile Cursor32Data, "files/cursor/cursor32.ani"
